### PR TITLE
Fix for GHC 8.2.

### LINKED ISSUE #20: hflags-0.4.2 does not compile
Trying to hflags with GHC 8.2.1, I get the following error:

~~~
Preprocessing library for hflags-0.4.2..
Building library for hflags-0.4.2..
[1 of 1] Compiling HFlags           ( HFlags.hs, dist/build/HFlags.o )

HFlags.hs:190:81: error:
    • Couldn't match type ‘Q Cxt’ with ‘[DerivClauseQ]’
      Expected type: [DerivClauseQ]
        Actual type: CxtQ
    • In the sixth argument of ‘dataD’, namely ‘(cxt [])’
      In a stmt of a 'do' block:
        dataDec <- dataD
                     (cxt []) dataName [] Nothing [normalC dataConstrName []] (cxt [])
      In the expression:
        do (name, short) <- if | length name' == 0
                                   -> fail "Flag's without names are not supported."
                               | length name' == 1 -> return (name', Just $ head name')
                               | length name' == 2 -> return (name', Nothing)
                               | name' !! 1 == ':' -> return (drop 2 name', Just $ head name')
                               | otherwise -> return (name', Nothing)
           defE <- defQ
           flagType <- case defE of
                         SigE _ flagType -> return $ return flagType
                         _ -> fail
                                "Default value for defineCustomFlag has to be an explicitly typed expression, like (12 :: Int)"
           moduleName <- fmap loc_module location
           ....
    |
190 |      dataDec <- dataD (cxt []) dataName [] Nothing [normalC dataConstrName []] (cxt [])
    |                                                                                 ^^^^^^
~~~~

### PR DESCRIPTION
**Pull request by mgajda**
This fixes #20 and makes it compile with GHC 8.2.
Trivial API revert.

### CODE REVIEW

**Comment by errge** [comment]
Thanks a lot!

**Comment by mgajda** [comment]
Could you please release it on Hackage?

**Comment by klao** [comment]
Released. Sorry for the delay and thanks again!
